
// Your web app's Firebase configuration
var firebaseConfig = {
    apiKey: "AIzaSyDtgYRAtg0kScM0rKo8iQ5DS5CYNIMxtPM",
    authDomain: "todo-list-ebfb6.firebaseapp.com",
    databaseURL: "https://todo-list-ebfb6-default-rtdb.firebaseio.com",
    projectId: "todo-list-ebfb6",
    storageBucket: "todo-list-ebfb6.appspot.com",
    messagingSenderId: "45942262733",
    appId: "1:45942262733:web:b2806ac6d7033fe4cf1284"
  };
  
  // Initialize Firebase
  var app = firebase.initializeApp(firebaseConfig);
  console.log(app.auth)
  

// Add this at the beginning of your script
document.addEventListener("DOMContentLoaded", function () {
    // Create a reference to the "todos" collection in the database
    var todosRef = firebase.database().ref("todos");
  
    // Listen for changes in the database and update the UI
    todosRef.on("child_added", function (snapshot) {
      var todo = snapshot.val();
      var todoKey = snapshot.key;
  
      var list = document.getElementById("listItems");
      var listElement = document.createElement("li");
      var listText = document.createTextNode(todo.text);
  
      listElement.appendChild(listText);
  
      var delbtn = document.createElement("button");
      var delbtnText = document.createTextNode("Delete");
      delbtn.appendChild(delbtnText);
      delbtn.setAttribute("onclick", "deltodo(this, '" + todoKey + "')");
      listElement.appendChild(delbtn);
  
      var Editbtn = document.createElement("button");
      var EditbtnText = document.createTextNode("Edit");
      Editbtn.appendChild(EditbtnText);
      Editbtn.setAttribute("onclick", "editTodo(this, '" + todoKey + "')");
      listElement.appendChild(Editbtn);
  
      list.appendChild(listElement);
    });
  });
  


  function addtodo() {
    var input = document.getElementById("todo-input");
    var list = document.getElementById("listItems");
  
    // Create a reference to your Firebase database
    var database = firebase.database();
  
    // Push the new todo to the database
    var newTodoRef = database.ref("todos").push({
      text: input.value
    });
  
    // Get the unique key generated by Firebase for this todo
    var todoKey = newTodoRef.key;
  
    var listElement = document.createElement("li");
    var listText = document.createTextNode(input.value);
  
    listElement.appendChild(listText);
  
    var delbtn = document.createElement("button");
    var delbtnText = document.createTextNode("Delete");
    delbtn.appendChild(delbtnText);
    delbtn.setAttribute("onclick", "deltodo(this, '" + todoKey + "')");
    listElement.appendChild(delbtn);
  
    var Editbtn = document.createElement("button");
    var EditbtnText = document.createTextNode("Edit");
    Editbtn.appendChild(EditbtnText);
    Editbtn.setAttribute("onclick", "editTodo(this, '" + todoKey + "')");
    listElement.appendChild(Editbtn);
  
    list.appendChild(listElement);
  
    input.value = "";
  }

  




  function deltodo(e, todoKey) {
    // Create a reference to the specific todo in the database
    var todoRef = firebase.database().ref("todos/" + todoKey);
  
    // Remove the todo from the database
    todoRef.remove();
  
    // Remove the todo from the UI
    e.parentNode.remove();
  }
  
  function editTodo(e, todoKey) {
    var currentli = e.parentNode.firstChild.nodeValue;
    var inputfield = prompt("Enter updated value", currentli);
  
    // Update the todo in the database
    firebase.database().ref("todos/" + todoKey).update({
      text: inputfield
    });
  
    e.parentNode.firstChild.nodeValue = inputfield;
  }
  